### PR TITLE
fixed issues with path to unicorn.rb

### PR DESCRIPTION
**Pull request by aliuk2012**
Assumes the user is in the correct directory to locate or create the
unicorn.rb file

P.S Thank you for this tutorial. Very much appreciated as I’m a freeBSD
/ FreeNAS newbie and trying to understand how it all works.

### CODE REVIEW

**Comment by voltechs** [comment]
Hey aliuk2012. I just noticed this PR :)

Cheers, I will look into it a bit further when I get home.

**Comment by aliuk2012** [comment]
No worries, any chance of helping out with a apache/passenger FreeNAS writeup?
 I tried this tutorial but I wasn't to comfortable with nginx and unicorn. I'm original from a ubuntu, apache, php stack background so freebsd, nginx and unicorn seemed a bit to foreign.

**Comment by voltechs** [comment]
Yea, I also came from PHP and Apache (back in the day) but I've always been (free)BSD based (OS X). I recommend you try to dive in to nginx at the very least, and I highly recommend BSD.

nginx is very powerful and lightweight, and unicorn is also in the same vein. I wrote this together with my friend @JimmayVV who was in your position as well. He might be up for helping with Apache.

**Comment by JimmayVV** [comment]
I have a video I need to edit of me performing all steps from beginning to end. Although I suppose I could upload the whole thing if YouTube were to allow me... I dunno it's like 2 hours long I'm dreading going through that monstrosity haha

**Comment by aliuk2012** [comment]
@voltechs I'm really loving FreeNAS and finding my way around BSD. The frustrasting part (also must enjoyable part) is trying to find tutorials for BSD and for specific configurations is hard to come by which is why I really appreciated your guide. What do you think about pulling together some guides for freebsd/freenas and various configs for Rails? It could all be shoved under this repo as it relates to rails setup.

@JimmayVV wow 2 hour video that would be extremely helpful. Do you need any help editing or perhaps I could write up a guide to go hand and hand with the video?

**Comment by aliuk2012** [comment]
@JimmayVV do you need any help with the video?

**Pull request merged**
